version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.7.7-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=<rabbitmq user>
      - RABBITMQ_DEFAULT_PASS=<rabbitmq password>
    ports:
      - "15672:15672"

  foundry_core_security_microservice:
    image: truecommerce/foundry.core.security.microservice:0.1
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SQLConnection=Server=<Core DB connection string>
      - RABBITMQ_CONNECTION=rabbitmq
      - RABBITMQ_USER=<rabbitmq user>
      - RABBITMQ_PASS=<rabbitmq password>
      - JwtSecret=<Jwt Secret>
      - JwtDefaultExpireMinutes=30
      - OverrideUserOnLogOn=true
      - UserSessionTimeout=30
    ports:
      - "30100:80"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
