version: '3.4'

services:
  demoservice.microservice:
    image: demoservicemicroservice
    build:
      context: .
      dockerfile: DemoService.Microservice/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SQLConnection=Server=10.0.1.27; Database=A1F Core 3.x; User Id=accellos; Password=accellos
    ports:
      - "80"