//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2019-10-02 8:47:41 PM
namespace DemoService.Client.OData.Models
{
    /// <summary>
    /// There are no comments for OrderSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("OrderSingle")]
    public partial class OrderSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Order>
    {
        /// <summary>
        /// Initialize a new OrderSingle object.
        /// </summary>
        public OrderSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new OrderSingle object.
        /// </summary>
        public OrderSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new OrderSingle object.
        /// </summary>
        public OrderSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Order> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Lines in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Lines")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::DemoService.Client.OData.Models.OrderLine> Lines
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Lines == null))
                {
                    this._Lines = Context.CreateQuery<global::DemoService.Client.OData.Models.OrderLine>(GetPath("Lines"));
                }
                return this._Lines;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DemoService.Client.OData.Models.OrderLine> _Lines;
    }
    /// <summary>
    /// There are no comments for Order in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Order")]
    public partial class Order : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="customerName">Initial value of CustomerName.</param>
        /// <param name="tenantId">Initial value of TenantId.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static Order CreateOrder(string customerName, string tenantId, global::System.Guid ID)
        {
            Order order = new Order();
            order.CustomerName = customerName;
            order.TenantId = tenantId;
            order.Id = ID;
            return order;
        }
        /// <summary>
        /// There are no comments for Property CustomerName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CustomerName")]
        public string CustomerName
        {
            get
            {
                return this._CustomerName;
            }
            set
            {
                this.OnCustomerNameChanging(value);
                this._CustomerName = value;
                this.OnCustomerNameChanged();
                this.OnPropertyChanged("CustomerName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _CustomerName;
        partial void OnCustomerNameChanging(string value);
        partial void OnCustomerNameChanged();
        /// <summary>
        /// There are no comments for Property TenantId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TenantId")]
        public string TenantId
        {
            get
            {
                return this._TenantId;
            }
            set
            {
                this.OnTenantIdChanging(value);
                this._TenantId = value;
                this.OnTenantIdChanged();
                this.OnPropertyChanged("TenantId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _TenantId;
        partial void OnTenantIdChanging(string value);
        partial void OnTenantIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property DateCreated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DateCreated")]
        public global::System.Nullable<global::System.DateTimeOffset> DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this.OnDateCreatedChanging(value);
                this._DateCreated = value;
                this.OnDateCreatedChanged();
                this.OnPropertyChanged("DateCreated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateCreated;
        partial void OnDateCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateCreatedChanged();
        /// <summary>
        /// There are no comments for Property UserCreated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserCreated")]
        public string UserCreated
        {
            get
            {
                return this._UserCreated;
            }
            set
            {
                this.OnUserCreatedChanging(value);
                this._UserCreated = value;
                this.OnUserCreatedChanged();
                this.OnPropertyChanged("UserCreated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _UserCreated;
        partial void OnUserCreatedChanging(string value);
        partial void OnUserCreatedChanged();
        /// <summary>
        /// There are no comments for Property DateModified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DateModified")]
        public global::System.Nullable<global::System.DateTimeOffset> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this.OnDateModifiedChanging(value);
                this._DateModified = value;
                this.OnDateModifiedChanged();
                this.OnPropertyChanged("DateModified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateModified;
        partial void OnDateModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateModifiedChanged();
        /// <summary>
        /// There are no comments for Property UserModified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserModified")]
        public string UserModified
        {
            get
            {
                return this._UserModified;
            }
            set
            {
                this.OnUserModifiedChanging(value);
                this._UserModified = value;
                this.OnUserModifiedChanged();
                this.OnPropertyChanged("UserModified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _UserModified;
        partial void OnUserModifiedChanging(string value);
        partial void OnUserModifiedChanged();
        /// <summary>
        /// There are no comments for Property Lines in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Lines")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::DemoService.Client.OData.Models.OrderLine> Lines
        {
            get
            {
                return this._Lines;
            }
            set
            {
                this.OnLinesChanging(value);
                this._Lines = value;
                this.OnLinesChanged();
                this.OnPropertyChanged("Lines");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::DemoService.Client.OData.Models.OrderLine> _Lines = new global::Microsoft.OData.Client.DataServiceCollection<global::DemoService.Client.OData.Models.OrderLine>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnLinesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::DemoService.Client.OData.Models.OrderLine> value);
        partial void OnLinesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OrderLineSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("OrderLineSingle")]
    public partial class OrderLineSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<OrderLine>
    {
        /// <summary>
        /// Initialize a new OrderLineSingle object.
        /// </summary>
        public OrderLineSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new OrderLineSingle object.
        /// </summary>
        public OrderLineSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new OrderLineSingle object.
        /// </summary>
        public OrderLineSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<OrderLine> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for OrderLine in the schema.
    /// </summary>
    /// <KeyProperties>
    /// LineNumber
    /// OrderId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("LineNumber", "OrderId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("OrderLine")]
    public partial class OrderLine : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new OrderLine object.
        /// </summary>
        /// <param name="orderId">Initial value of OrderId.</param>
        /// <param name="lineNumber">Initial value of LineNumber.</param>
        /// <param name="itemName">Initial value of ItemName.</param>
        /// <param name="itemQty">Initial value of ItemQty.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static OrderLine CreateOrderLine(global::System.Guid orderId, int lineNumber, string itemName, decimal itemQty)
        {
            OrderLine orderLine = new OrderLine();
            orderLine.OrderId = orderId;
            orderLine.LineNumber = lineNumber;
            orderLine.ItemName = itemName;
            orderLine.ItemQty = itemQty;
            return orderLine;
        }
        /// <summary>
        /// There are no comments for Property OrderId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("OrderId")]
        public global::System.Guid OrderId
        {
            get
            {
                return this._OrderId;
            }
            set
            {
                this.OnOrderIdChanging(value);
                this._OrderId = value;
                this.OnOrderIdChanged();
                this.OnPropertyChanged("OrderId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _OrderId;
        partial void OnOrderIdChanging(global::System.Guid value);
        partial void OnOrderIdChanged();
        /// <summary>
        /// There are no comments for Property LineNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LineNumber")]
        public int LineNumber
        {
            get
            {
                return this._LineNumber;
            }
            set
            {
                this.OnLineNumberChanging(value);
                this._LineNumber = value;
                this.OnLineNumberChanged();
                this.OnPropertyChanged("LineNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private int _LineNumber;
        partial void OnLineNumberChanging(int value);
        partial void OnLineNumberChanged();
        /// <summary>
        /// There are no comments for Property ItemName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ItemName")]
        public string ItemName
        {
            get
            {
                return this._ItemName;
            }
            set
            {
                this.OnItemNameChanging(value);
                this._ItemName = value;
                this.OnItemNameChanged();
                this.OnPropertyChanged("ItemName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _ItemName;
        partial void OnItemNameChanging(string value);
        partial void OnItemNameChanged();
        /// <summary>
        /// There are no comments for Property ItemQty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ItemQty")]
        public decimal ItemQty
        {
            get
            {
                return this._ItemQty;
            }
            set
            {
                this.OnItemQtyChanging(value);
                this._ItemQty = value;
                this.OnItemQtyChanged();
                this.OnPropertyChanged("ItemQty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private decimal _ItemQty;
        partial void OnItemQtyChanging(decimal value);
        partial void OnItemQtyChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::DemoService.Client.OData.Models.Order as global::DemoService.Client.OData.Models.OrderSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::DemoService.Client.OData.Models.OrderSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DemoService.Client.OData.Models.Order> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::DemoService.Client.OData.Models.OrderSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DemoService.Client.OData.Models.Order as global::DemoService.Client.OData.Models.OrderSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::DemoService.Client.OData.Models.OrderSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DemoService.Client.OData.Models.Order> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::DemoService.Client.OData.Models.OrderSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DemoService.Client.OData.Models.OrderLine as global::DemoService.Client.OData.Models.OrderLineSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::DemoService.Client.OData.Models.OrderLineSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DemoService.Client.OData.Models.OrderLine> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::DemoService.Client.OData.Models.OrderLineSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DemoService.Client.OData.Models.OrderLine as global::DemoService.Client.OData.Models.OrderLineSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="lineNumber">The value of lineNumber</param>
        /// <param name="orderId">The value of orderId</param>
        public static global::DemoService.Client.OData.Models.OrderLineSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DemoService.Client.OData.Models.OrderLine> source,
            int lineNumber, 
            global::System.Guid orderId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "LineNumber", lineNumber }, 
                { "OrderId", orderId }
            };
            return new global::DemoService.Client.OData.Models.OrderLineSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace DemoService.Client.OData.Shared.Models
{
    /// <summary>
    /// There are no comments for ExportParameters in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ExportParameters")]
    public partial class ExportParameters : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property ProductId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProductId")]
        public string ProductId
        {
            get
            {
                return this._ProductId;
            }
            set
            {
                this.OnProductIdChanging(value);
                this._ProductId = value;
                this.OnProductIdChanged();
                this.OnPropertyChanged("ProductId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _ProductId;
        partial void OnProductIdChanging(string value);
        partial void OnProductIdChanged();
        /// <summary>
        /// There are no comments for Property AdditionalId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AdditionalId")]
        public string AdditionalId
        {
            get
            {
                return this._AdditionalId;
            }
            set
            {
                this.OnAdditionalIdChanging(value);
                this._AdditionalId = value;
                this.OnAdditionalIdChanged();
                this.OnPropertyChanged("AdditionalId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _AdditionalId;
        partial void OnAdditionalIdChanging(string value);
        partial void OnAdditionalIdChanged();
        /// <summary>
        /// There are no comments for Property Entities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Entities")]
        public global::System.Collections.ObjectModel.ObservableCollection<global::System.Guid> Entities
        {
            get
            {
                return this._Entities;
            }
            set
            {
                this.OnEntitiesChanging(value);
                this._Entities = value;
                this.OnEntitiesChanged();
                this.OnPropertyChanged("Entities");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Collections.ObjectModel.ObservableCollection<global::System.Guid> _Entities = new global::System.Collections.ObjectModel.ObservableCollection<global::System.Guid>();
        partial void OnEntitiesChanging(global::System.Collections.ObjectModel.ObservableCollection<global::System.Guid> value);
        partial void OnEntitiesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for KeyValueStringPair in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("KeyValueStringPair")]
    public partial class KeyValueStringPair : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new KeyValueStringPair object.
        /// </summary>
        /// <param name="key">Initial value of Key.</param>
        /// <param name="value">Initial value of Value.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static KeyValueStringPair CreateKeyValueStringPair(string key, string value)
        {
            KeyValueStringPair keyValueStringPair = new KeyValueStringPair();
            keyValueStringPair.Key = key;
            keyValueStringPair.Value = value;
            return keyValueStringPair;
        }
        /// <summary>
        /// There are no comments for Property Key in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Key")]
        public string Key
        {
            get
            {
                return this._Key;
            }
            set
            {
                this.OnKeyChanging(value);
                this._Key = value;
                this.OnKeyChanged();
                this.OnPropertyChanged("Key");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Key;
        partial void OnKeyChanging(string value);
        partial void OnKeyChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Value")]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LocalizableError in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("LocalizableError")]
    public partial class LocalizableError : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property ErrorId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ErrorId")]
        public string ErrorId
        {
            get
            {
                return this._ErrorId;
            }
            set
            {
                this.OnErrorIdChanging(value);
                this._ErrorId = value;
                this.OnErrorIdChanged();
                this.OnPropertyChanged("ErrorId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _ErrorId;
        partial void OnErrorIdChanging(string value);
        partial void OnErrorIdChanged();
        /// <summary>
        /// There are no comments for Property ErrorMessage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ErrorMessage")]
        public string ErrorMessage
        {
            get
            {
                return this._ErrorMessage;
            }
            set
            {
                this.OnErrorMessageChanging(value);
                this._ErrorMessage = value;
                this.OnErrorMessageChanged();
                this.OnPropertyChanged("ErrorMessage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _ErrorMessage;
        partial void OnErrorMessageChanging(string value);
        partial void OnErrorMessageChanged();
        /// <summary>
        /// There are no comments for Property Parameters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Parameters")]
        public global::System.Collections.ObjectModel.ObservableCollection<string> Parameters
        {
            get
            {
                return this._Parameters;
            }
            set
            {
                this.OnParametersChanging(value);
                this._Parameters = value;
                this.OnParametersChanged();
                this.OnPropertyChanged("Parameters");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _Parameters = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnParametersChanging(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnParametersChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for TenantActionSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TenantActionSingle")]
    public partial class TenantActionSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<TenantAction>
    {
        /// <summary>
        /// Initialize a new TenantActionSingle object.
        /// </summary>
        public TenantActionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new TenantActionSingle object.
        /// </summary>
        public TenantActionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new TenantActionSingle object.
        /// </summary>
        public TenantActionSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<TenantAction> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for TenantAction in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("TenantAction")]
    public partial class TenantAction : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TenantAction object.
        /// </summary>
        /// <param name="tenantId">Initial value of TenantId.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static TenantAction CreateTenantAction(string tenantId, global::System.Guid ID)
        {
            TenantAction tenantAction = new TenantAction();
            tenantAction.TenantId = tenantId;
            tenantAction.Id = ID;
            return tenantAction;
        }
        /// <summary>
        /// There are no comments for Property TenantId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TenantId")]
        public string TenantId
        {
            get
            {
                return this._TenantId;
            }
            set
            {
                this.OnTenantIdChanging(value);
                this._TenantId = value;
                this.OnTenantIdChanged();
                this.OnPropertyChanged("TenantId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _TenantId;
        partial void OnTenantIdChanging(string value);
        partial void OnTenantIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property DateCreated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DateCreated")]
        public global::System.Nullable<global::System.DateTimeOffset> DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this.OnDateCreatedChanging(value);
                this._DateCreated = value;
                this.OnDateCreatedChanged();
                this.OnPropertyChanged("DateCreated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateCreated;
        partial void OnDateCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateCreatedChanged();
        /// <summary>
        /// There are no comments for Property UserCreated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserCreated")]
        public string UserCreated
        {
            get
            {
                return this._UserCreated;
            }
            set
            {
                this.OnUserCreatedChanging(value);
                this._UserCreated = value;
                this.OnUserCreatedChanged();
                this.OnPropertyChanged("UserCreated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _UserCreated;
        partial void OnUserCreatedChanging(string value);
        partial void OnUserCreatedChanged();
        /// <summary>
        /// There are no comments for Property DateModified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DateModified")]
        public global::System.Nullable<global::System.DateTimeOffset> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this.OnDateModifiedChanging(value);
                this._DateModified = value;
                this.OnDateModifiedChanged();
                this.OnPropertyChanged("DateModified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateModified;
        partial void OnDateModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateModifiedChanged();
        /// <summary>
        /// There are no comments for Property UserModified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserModified")]
        public string UserModified
        {
            get
            {
                return this._UserModified;
            }
            set
            {
                this.OnUserModifiedChanging(value);
                this._UserModified = value;
                this.OnUserModifiedChanged();
                this.OnPropertyChanged("UserModified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _UserModified;
        partial void OnUserModifiedChanging(string value);
        partial void OnUserModifiedChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::DemoService.Client.OData.Shared.Models.TenantAction as global::DemoService.Client.OData.Shared.Models.TenantActionSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::DemoService.Client.OData.Shared.Models.TenantActionSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DemoService.Client.OData.Shared.Models.TenantAction> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::DemoService.Client.OData.Shared.Models.TenantActionSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DemoService.Client.OData.Shared.Models.TenantAction as global::DemoService.Client.OData.Shared.Models.TenantActionSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::DemoService.Client.OData.Shared.Models.TenantActionSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DemoService.Client.OData.Shared.Models.TenantAction> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::DemoService.Client.OData.Shared.Models.TenantActionSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace DemoService.Client.OData.Context
{
    /// <summary>
    /// There are no comments for DemoServiceODataContext in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DemoServiceODataContext")]
    public partial class DemoServiceODataContext : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new DemoServiceODataContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public DemoServiceODataContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Foundry.Core.Shared.Models", "DemoService.Client.OData.Shared.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "DemoService.Core.Models", "DemoService.Client.OData.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "DemoService.Client.OData.Context");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("DemoService.Client.OData.Shared.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Foundry.Core.Shared.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Foundry.Core.Shared.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("DemoService.Client.OData.Context", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            if (clientType.Namespace.Equals("DemoService.Client.OData.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("DemoService.Core.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("DemoService.Core.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Orders")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::DemoService.Client.OData.Models.Order> Orders
        {
            get
            {
                if ((this._Orders == null))
                {
                    this._Orders = base.CreateQuery<global::DemoService.Client.OData.Models.Order>("Orders");
                }
                return this._Orders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DemoService.Client.OData.Models.Order> _Orders;
        /// <summary>
        /// There are no comments for OrderLines in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("OrderLines")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::DemoService.Client.OData.Models.OrderLine> OrderLines
        {
            get
            {
                if ((this._OrderLines == null))
                {
                    this._OrderLines = base.CreateQuery<global::DemoService.Client.OData.Models.OrderLine>("OrderLines");
                }
                return this._OrderLines;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DemoService.Client.OData.Models.OrderLine> _OrderLines;
        /// <summary>
        /// There are no comments for TenantActions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TenantActions")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::DemoService.Client.OData.Shared.Models.TenantAction> TenantActions
        {
            get
            {
                if ((this._TenantActions == null))
                {
                    this._TenantActions = base.CreateQuery<global::DemoService.Client.OData.Shared.Models.TenantAction>("TenantActions");
                }
                return this._TenantActions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DemoService.Client.OData.Shared.Models.TenantAction> _TenantActions;
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToOrders(global::DemoService.Client.OData.Models.Order order)
        {
            base.AddObject("Orders", order);
        }
        /// <summary>
        /// There are no comments for OrderLines in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToOrderLines(global::DemoService.Client.OData.Models.OrderLine orderLine)
        {
            base.AddObject("OrderLines", orderLine);
        }
        /// <summary>
        /// There are no comments for TenantActions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToTenantActions(global::DemoService.Client.OData.Shared.Models.TenantAction tenantAction)
        {
            base.AddObject("TenantActions", tenantAction);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""DemoService.Core.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Order"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""CustomerName"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""TenantId"" Type=""Edm.String"" Nullable=""false"" MaxLength=""255"" />
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""DateCreated"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""UserCreated"" Type=""Edm.String"" />
        <Property Name=""DateModified"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""UserModified"" Type=""Edm.String"" />
        <NavigationProperty Name=""Lines"" Type=""Collection(DemoService.Core.Models.OrderLine)"" />
      </EntityType>
      <EntityType Name=""OrderLine"">
        <Key>
          <PropertyRef Name=""LineNumber"" />
          <PropertyRef Name=""OrderId"" />
        </Key>
        <Property Name=""OrderId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""LineNumber"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""ItemName"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""ItemQty"" Type=""Edm.Decimal"" Nullable=""false"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Foundry.Core.Shared.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <ComplexType Name=""ExportParameters"">
        <Property Name=""ProductId"" Type=""Edm.String"" />
        <Property Name=""AdditionalId"" Type=""Edm.String"" />
        <Property Name=""Entities"" Type=""Collection(Edm.Guid)"" Nullable=""false"" />
      </ComplexType>
      <ComplexType Name=""KeyValueStringPair"">
        <Property Name=""Key"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""Value"" Type=""Edm.String"" Nullable=""false"" />
      </ComplexType>
      <ComplexType Name=""LocalizableError"">
        <Property Name=""ErrorId"" Type=""Edm.String"" />
        <Property Name=""ErrorMessage"" Type=""Edm.String"" />
        <Property Name=""Parameters"" Type=""Collection(Edm.String)"" />
      </ComplexType>
      <EntityType Name=""TenantAction"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""TenantId"" Type=""Edm.String"" Nullable=""false"" MaxLength=""255"" />
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""DateCreated"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""UserCreated"" Type=""Edm.String"" />
        <Property Name=""DateModified"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""UserModified"" Type=""Edm.String"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <Action Name=""Import"">
        <Parameter Name=""kind"" Type=""Edm.String"" />
        <Parameter Name=""overwriteExisting"" Type=""Edm.Boolean"" Nullable=""false"" />
      </Action>
      <Action Name=""Export"">
        <Parameter Name=""kind"" Type=""Edm.String"" />
        <Parameter Name=""additionalId"" Type=""Edm.String"" />
        <Parameter Name=""productId"" Type=""Edm.String"" />
        <Parameter Name=""ids"" Type=""Collection(Edm.Guid)"" Nullable=""false"" />
        <ReturnType Type=""Edm.Stream"" Nullable=""false"" />
      </Action>
      <EntityContainer Name=""DemoServiceODataContext"">
        <EntitySet Name=""Orders"" EntityType=""DemoService.Core.Models.Order"">
          <NavigationPropertyBinding Path=""Lines"" Target=""OrderLines"" />
        </EntitySet>
        <EntitySet Name=""OrderLines"" EntityType=""DemoService.Core.Models.OrderLine"" />
        <EntitySet Name=""TenantActions"" EntityType=""Foundry.Core.Shared.Models.TenantAction"" />
        <ActionImport Name=""Import"" Action=""Default.Import"" />
        <ActionImport Name=""Export"" Action=""Default.Export"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;
                    
                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
        /// <summary>
        /// There are no comments for Import in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("Import")]
        public global::Microsoft.OData.Client.DataServiceActionQuery Import(string kind, bool overwriteExisting)
        {
            return new global::Microsoft.OData.Client.DataServiceActionQuery(this, this.BaseUri.OriginalString.Trim('/') + "/Import", new global::Microsoft.OData.Client.BodyOperationParameter("kind", kind),
                    new global::Microsoft.OData.Client.BodyOperationParameter("overwriteExisting", overwriteExisting));
        }
        /// <summary>
        /// There are no comments for Export in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("Export")]
        public global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::Microsoft.OData.Client.DataServiceStreamLink> Export(string kind, string additionalId, string productId, global::System.Collections.Generic.ICollection<global::System.Guid> ids)
        {
            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::Microsoft.OData.Client.DataServiceStreamLink>(this, this.BaseUri.OriginalString.Trim('/') + "/Export", new global::Microsoft.OData.Client.BodyOperationParameter("kind", kind),
                    new global::Microsoft.OData.Client.BodyOperationParameter("additionalId", additionalId),
                    new global::Microsoft.OData.Client.BodyOperationParameter("productId", productId),
                    new global::Microsoft.OData.Client.BodyOperationParameter("ids", ids));
        }
    }
}
